export default [{
  "idMeal": "52779",
  "strMeal": "Cream Cheese Tart",
  "strDrinkAlternate": null,
  "strCategory": "Starter",
  "strArea": "Unknown",
  "strInstructions": "Crust: make a dough from 250g flour (I like mixing different flours like plain and wholegrain spelt flour), 125g butter, 1 egg and a pinch of salt, press it into a tart form and place it in the fridge. Filling: stir 300g cream cheese and 100ml milk until smooth, add in 3 eggs, 100g grated parmesan cheese and season with salt, pepper and nutmeg. Take the crust out of the fridge and prick the bottom with a fork. Pour in the filling and bake at 175 degrees C for about 25 minutes. Cover the tart with some aluminium foil after half the time. In the mean time, slice about 350g mini tomatoes. In a small pan heat 3tbsp olive oil, 3tbsp white vinegar, 1 tbsp honey, salt and pepper and combine well. Pour over the tomato slices and mix well. With a spoon, place the tomato slices on the tart, avoiding too much liquid on it. Decorate with basil leaves and enjoy",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/wurrux1468416624.jpg",
  "strTags": "Tart,Savory",
  "strYoutube": "https://www.youtube.com/watch?v=UhQPwO4uymo",
  "strIngredient1": "Flour",
  "strIngredient2": "Butter",
  "strIngredient3": "Egg",
  "strIngredient4": "Salt",
  "strIngredient5": "Cheese",
  "strIngredient6": "Milk",
  "strIngredient7": "Eggs",
  "strIngredient8": "Parmesan Cheese",
  "strIngredient9": "Plum tomatoes",
  "strIngredient10": "White Vinegar",
  "strIngredient11": "Honey",
  "strIngredient12": "Basil",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": null,
  "strIngredient17": null,
  "strIngredient18": null,
  "strIngredient19": null,
  "strIngredient20": null,
  "strMeasure1": "250g",
  "strMeasure2": "125g",
  "strMeasure3": "1",
  "strMeasure4": "Pinch",
  "strMeasure5": "300g",
  "strMeasure6": "100ml milk",
  "strMeasure7": "3",
  "strMeasure8": "100g",
  "strMeasure9": "350g",
  "strMeasure10": "3tbsp",
  "strMeasure11": "1 tbsp",
  "strMeasure12": "Topping",
  "strMeasure13": "",
  "strMeasure14": "",
  "strMeasure15": "",
  "strMeasure16": null,
  "strMeasure17": null,
  "strMeasure18": null,
  "strMeasure19": null,
  "strMeasure20": null,
  "strSource": "https://www.instagram.com/p/BHyuMZ1hZX0",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
}, {
  "idMeal": "53057",
  "strMeal": "Traditional Croatian Goulash",
  "strDrinkAlternate": null,
  "strCategory": "Beef",
  "strArea": "Croatian",
  "strInstructions": "Clean the meat from the veins if there are some and cut it into smaller pieces, 3 × 3 cm. Marinate the meat in the mustard and spices and let it sit in the refrigerator for one hour\r\nHeat one tablespoon of pork fat or vegetable oil in a pot and fry the meat on all sides until it gets browned. Once the meat is cooked, transfer it to a plate and add another tablespoon of fat to the pot\r\nCut the onions very fine, peel the carrots and shred it using a grater. Cook the onions and carrots over low heat for 15 minutes. You can salt the vegetables a little to make them soften faster\r\nOnce the vegetables have browned and become slightly mushy, add the meat and bay leaves and garlic. Pour over with wine and simmer for 10-15 minutes to allow the alcohol to evaporate. Now is the right time to add 2/3 the amount of liquid\r\nCover the pot and cook over low heat for an hour, stirring occasionally. After the first hour, pour over the rest of the water or stock and cook for another 30-45 minutes\r\nAllow the stew to cool slightly and serve it with a sprinkle of chopped parsley and few slices of fresh hot pepper if you like to spice it up a bit\r\nSlice ​​some fresh bread, season the salad and simply enjoying these wonderful flavors",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/n1hcou1628770088.jpg",
  "strTags": "Soup",
  "strYoutube": "https://www.youtube.com/watch?v=ipEz5u2T7KM",
  "strIngredient1": "Beef",
  "strIngredient2": "Onions",
  "strIngredient3": "Carrots",
  "strIngredient4": "Garlic",
  "strIngredient5": "Bay Leaf",
  "strIngredient6": "Red Wine",
  "strIngredient7": "Water",
  "strIngredient8": "Mustard",
  "strIngredient9": "Salt",
  "strIngredient10": "Pepper",
  "strIngredient11": "Paprika",
  "strIngredient12": "Vegetable Oil",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "500g",
  "strMeasure2": "2 chopped",
  "strMeasure3": "2 chopped",
  "strMeasure4": "2 cloves",
  "strMeasure5": "2",
  "strMeasure6": "200ml",
  "strMeasure7": "2 Litres",
  "strMeasure8": "3 tbs",
  "strMeasure9": "1tbsp",
  "strMeasure10": "1/2 tsp",
  "strMeasure11": "1/2 tsp",
  "strMeasure12": "2 tbs",
  "strMeasure13": " ",
  "strMeasure14": " ",
  "strMeasure15": " ",
  "strMeasure16": " ",
  "strMeasure17": " ",
  "strMeasure18": " ",
  "strMeasure19": " ",
  "strMeasure20": " ",
  "strSource": "https://www.chasingthedonkey.com/croatian-recipes-traditional-croatian-goulash/",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
}, {
  "idMeal": "52914",
  "strMeal": "Boulangère Potatoes",
  "strDrinkAlternate": null,
  "strCategory": "Side",
  "strArea": "French",
  "strInstructions": "Heat oven to 200C/fan 180C/gas 6. Fry the onions and thyme sprigs in the oil until softened and lightly coloured (about 5 mins).\r\nSpread a layer of potatoes over the base of a 1.5-litre oiled gratin dish. Sprinkle over a few onions (see picture, above) and continue layering, finishing with a layer of potatoes. Pour over the stock and bake for 50-60 mins until the potatoes are cooked and the top is golden and crisp.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/qywups1511796761.jpg",
  "strTags": "SideDish",
  "strYoutube": "https://www.youtube.com/watch?v=gcXPruv1Mjg",
  "strIngredient1": "Onions",
  "strIngredient2": "Thyme",
  "strIngredient3": "Olive Oil",
  "strIngredient4": "Potatoes",
  "strIngredient5": "Vegetable Stock",
  "strIngredient6": "",
  "strIngredient7": "",
  "strIngredient8": "",
  "strIngredient9": "",
  "strIngredient10": "",
  "strIngredient11": "",
  "strIngredient12": "",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "2 finely chopped",
  "strMeasure2": "sprigs of fresh",
  "strMeasure3": "2 tbs",
  "strMeasure4": "1.5kg",
  "strMeasure5": "425g",
  "strMeasure6": "",
  "strMeasure7": "",
  "strMeasure8": "",
  "strMeasure9": "",
  "strMeasure10": "",
  "strMeasure11": "",
  "strMeasure12": "",
  "strMeasure13": "",
  "strMeasure14": "",
  "strMeasure15": "",
  "strMeasure16": "",
  "strMeasure17": "",
  "strMeasure18": "",
  "strMeasure19": "",
  "strMeasure20": "",
  "strSource": "https://www.bbcgoodfood.com/recipes/5056/boulangre-potatoes",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
}, {
  "idMeal": "53065",
  "strMeal": "Sushi",
  "strDrinkAlternate": null,
  "strCategory": "Seafood",
  "strArea": "Japanese",
  "strInstructions": "STEP 1\r\nTO MAKE SUSHI ROLLS: Pat out some rice. Lay a nori sheet on the mat, shiny-side down. Dip your hands in the vinegared water, then pat handfuls of rice on top in a 1cm thick layer, leaving the furthest edge from you clear.\r\n\r\nSTEP 2\r\nSpread over some Japanese mayonnaise. Use a spoon to spread out a thin layer of mayonnaise down the middle of the rice.\r\n\r\nSTEP 3\r\nAdd the filling. Get your child to top the mayonnaise with a line of their favourite fillings – here we’ve used tuna and cucumber.\r\n\r\nSTEP 4\r\nRoll it up. Lift the edge of the mat over the rice, applying a little pressure to keep everything in a tight roll.\r\n\r\nSTEP 5\r\nStick down the sides like a stamp. When you get to the edge without any rice, brush with a little water and continue to roll into a tight roll.\r\n\r\nSTEP 6\r\nWrap in cling film. Remove the mat and roll tightly in cling film before a grown-up cuts the sushi into thick slices, then unravel the cling film.\r\n\r\nSTEP 7\r\nTO MAKE PRESSED SUSHI: Layer over some smoked salmon. Line a loaf tin with cling film, then place a thin layer of smoked salmon inside on top of the cling film.\r\n\r\nSTEP 8\r\nCover with rice and press down. Press about 3cm of rice over the fish, fold the cling film over and press down as much as you can, using another tin if you have one.\r\n\r\nSTEP 9\r\nTip it out like a sandcastle. Turn block of sushi onto a chopping board. Get a grown-up to cut into fingers, then remove the cling film.\r\n\r\nSTEP 10\r\nTO MAKE SUSHI BALLS: Choose your topping. Get a small square of cling film and place a topping, like half a prawn or a small piece of smoked salmon, on it. Use damp hands to roll walnut-sized balls of rice and place on the topping.\r\n\r\nSTEP 11\r\nMake into tight balls. Bring the corners of the cling film together and tighten into balls by twisting it up, then unwrap and serve.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
  "strTags": null,
  "strYoutube": "https://www.youtube.com/watch?v=ub68OxEypaY",
  "strIngredient1": "Sushi Rice",
  "strIngredient2": "Rice wine",
  "strIngredient3": "Caster Sugar",
  "strIngredient4": "Mayonnaise",
  "strIngredient5": "Rice wine",
  "strIngredient6": "Soy Sauce",
  "strIngredient7": "Cucumber",
  "strIngredient8": "",
  "strIngredient9": "",
  "strIngredient10": "",
  "strIngredient11": "",
  "strIngredient12": "",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "300ml ",
  "strMeasure2": "100ml",
  "strMeasure3": "2 tbs",
  "strMeasure4": "3 tbs",
  "strMeasure5": "1 tbs",
  "strMeasure6": "1 tbs",
  "strMeasure7": "1",
  "strMeasure8": " ",
  "strMeasure9": " ",
  "strMeasure10": " ",
  "strMeasure11": " ",
  "strMeasure12": " ",
  "strMeasure13": " ",
  "strMeasure14": " ",
  "strMeasure15": " ",
  "strMeasure16": " ",
  "strMeasure17": " ",
  "strMeasure18": " ",
  "strMeasure19": " ",
  "strMeasure20": " ",
  "strSource": "https://www.bbcgoodfood.com/recipes/simple-sushi",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
}, {
  "idMeal": "52969",
  "strMeal": "Chakchouka ",
  "strDrinkAlternate": null,
  "strCategory": "Miscellaneous",
  "strArea": "Tunisian",
  "strInstructions": "In a large cast iron skillet or sauté pan with a lid, heat oil over medium high heat. Add the onion and sauté for 2-3 minutes, until softened. Add the peppers and garlic, and sauté for an additional 3-5 minutes. Add the tomatoes, cumin, paprika, salt, and chili powder. Mix well and bring the mixture to a simmer. Reduce the heat to medium low and continue to simmer, uncovered, 10-15 minutes until the mixture has thickened to your desired consistency. (Taste the sauce at this point and adjust for salt and spice, as desired.) Using the back of a spoon, make four craters in the mixture, large enough to hold an egg. Crack one egg into each of the craters. Cover the skillet and simmer for 5-7 minutes, until the eggs have set. Serve immediately with crusty bread or pita.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/gpz67p1560458984.jpg",
  "strTags": null,
  "strYoutube": "https://www.youtube.com/watch?v=EHKNu93MSx4",
  "strIngredient1": "Tomatoes",
  "strIngredient2": "Olive Oil",
  "strIngredient3": "Onion",
  "strIngredient4": "Red Pepper",
  "strIngredient5": "Green Pepper",
  "strIngredient6": "Garlic",
  "strIngredient7": "Cumin",
  "strIngredient8": "Paprika",
  "strIngredient9": "Salt",
  "strIngredient10": "Chili Powder",
  "strIngredient11": "Eggs",
  "strIngredient12": "",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "4",
  "strMeasure2": "2 tbs",
  "strMeasure3": "1 Diced",
  "strMeasure4": "1 sliced",
  "strMeasure5": "1 sliced",
  "strMeasure6": "3 Cloves Crushed",
  "strMeasure7": "1 tsp ",
  "strMeasure8": "1 tsp ",
  "strMeasure9": "3/4 teaspoon",
  "strMeasure10": "1/2 teaspoon",
  "strMeasure11": "4",
  "strMeasure12": " ",
  "strMeasure13": " ",
  "strMeasure14": " ",
  "strMeasure15": " ",
  "strMeasure16": " ",
  "strMeasure17": " ",
  "strMeasure18": " ",
  "strMeasure19": " ",
  "strMeasure20": " ",
  "strSource": "https://www.curiouscuisiniere.com/chakchouka/",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
}, {
  "idMeal": "52959",
  "strMeal": "Baked salmon with fennel & tomatoes",
  "strDrinkAlternate": null,
  "strCategory": "Seafood",
  "strArea": "British",
  "strInstructions": "Heat oven to 180C/fan 160C/gas 4. Trim the fronds from the fennel and set aside. Cut the fennel bulbs in half, then cut each half into 3 wedges. Cook in boiling salted water for 10 mins, then drain well. Chop the fennel fronds roughly, then mix with the parsley and lemon zest.\r\n\r\nSpread the drained fennel over a shallow ovenproof dish, then add the tomatoes. Drizzle with olive oil, then bake for 10 mins. Nestle the salmon among the veg, sprinkle with lemon juice, then bake 15 mins more until the fish is just cooked. Scatter over the parsley and serve.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/1548772327.jpg",
  "strTags": "Paleo,Keto,HighFat,Baking,LowCarbs",
  "strYoutube": "https://www.youtube.com/watch?v=xvPR2Tfw5k0",
  "strIngredient1": "Fennel",
  "strIngredient2": "Parsley",
  "strIngredient3": "Lemon",
  "strIngredient4": "Cherry Tomatoes",
  "strIngredient5": "Olive Oil",
  "strIngredient6": "Salmon",
  "strIngredient7": "Black Olives",
  "strIngredient8": "",
  "strIngredient9": "",
  "strIngredient10": "",
  "strIngredient11": "",
  "strIngredient12": "",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "2 medium",
  "strMeasure2": "2 tbs chopped",
  "strMeasure3": "Juice of 1",
  "strMeasure4": "175g",
  "strMeasure5": "1 tbs",
  "strMeasure6": "350g",
  "strMeasure7": "to serve",
  "strMeasure8": "",
  "strMeasure9": "",
  "strMeasure10": "",
  "strMeasure11": "",
  "strMeasure12": "",
  "strMeasure13": "",
  "strMeasure14": "",
  "strMeasure15": "",
  "strMeasure16": "",
  "strMeasure17": "",
  "strMeasure18": "",
  "strMeasure19": "",
  "strMeasure20": "",
  "strSource": "https://www.bbcgoodfood.com/recipes/7745/baked-salmon-with-fennel-and-tomatoes",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
}, {
  "idMeal": "52819",
  "strMeal": "Cajun spiced fish tacos",
  "strDrinkAlternate": null,
  "strCategory": "Seafood",
  "strArea": "Mexican",
  "strInstructions": "Cooking in a cajun spice and cayenne pepper marinade makes this fish super succulent and flavoursome. Top with a zesty dressing and serve in a tortilla for a quick, fuss-free main that's delightfully summery.\r\n\r\nOn a large plate, mix the cajun spice and cayenne pepper with a little seasoning and use to coat the fish all over.\r\n\r\nHeat a little oil in a frying pan, add in the fish and cook over a medium heat until golden. Reduce the heat and continue frying until the fish is cooked through, about 10 minutes. Cook in batches if you don’t have enough room in the pan.\r\n\r\nMeanwhile, prepare the dressing by combining all the ingredients with a little seasoning.\r\nSoften the tortillas by heating in the microwave for 5-10 seconds. Pile high with the avocado, lettuce and spring onion, add a spoonful of salsa, top with large flakes of fish and drizzle over the dressing.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
  "strTags": "Spicy,Fish",
  "strYoutube": "https://www.youtube.com/watch?v=N4EdUt0Ou48",
  "strIngredient1": "cajun",
  "strIngredient2": "cayenne pepper",
  "strIngredient3": "white fish",
  "strIngredient4": "vegetable oil",
  "strIngredient5": "flour tortilla",
  "strIngredient6": "avocado",
  "strIngredient7": "little gem lettuce",
  "strIngredient8": "spring onion",
  "strIngredient9": "salsa",
  "strIngredient10": "sour cream",
  "strIngredient11": "lemon",
  "strIngredient12": "garlic",
  "strIngredient13": "",
  "strIngredient14": "",
  "strIngredient15": "",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "2 tbsp",
  "strMeasure2": "1 tsp",
  "strMeasure3": "4 fillets",
  "strMeasure4": "1 tsp",
  "strMeasure5": "8",
  "strMeasure6": "1 sliced",
  "strMeasure7": "2 shredded",
  "strMeasure8": "4 shredded",
  "strMeasure9": "1 x 300ml",
  "strMeasure10": "1 pot",
  "strMeasure11": "1",
  "strMeasure12": "1 clove finely chopped",
  "strMeasure13": "",
  "strMeasure14": "",
  "strMeasure15": "",
  "strMeasure16": "",
  "strMeasure17": "",
  "strMeasure18": "",
  "strMeasure19": "",
  "strMeasure20": "",
  "strSource": "https://realfood.tesco.com/recipes/cajun-spiced-fish-tacos.html",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
}, {
  "idMeal": "52874",
  "strMeal": "Beef and Mustard Pie",
  "strDrinkAlternate": null,
  "strCategory": "Beef",
  "strArea": "British",
  "strInstructions": "Preheat the oven to 150C/300F/Gas 2.\r\nToss the beef and flour together in a bowl with some salt and black pepper.\r\nHeat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole.\r\nFry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef.\r\nReturn the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and season well with salt and pepper.\r\nCover with a lid and place in the oven for two hours.\r\nRemove from the oven, check the seasoning and set aside to cool. Remove the thyme.\r\nWhen the beef is cool and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6.\r\nTransfer the beef to a pie dish, brush the rim with the beaten egg yolks and lay the pastry over the top. Brush the top of the pastry with more beaten egg.\r\nTrim the pastry so there is just enough excess to crimp the edges, then place in the oven and bake for 30 minutes, or until the pastry is golden-brown and cooked through.\r\nFor the green beans, bring a saucepan of salted water to the boil, add the beans and cook for 4-5 minutes, or until just tender.\r\nDrain and toss with the butter, then season with black pepper.\r\nTo serve, place a large spoonful of pie onto each plate with some green beans alongside.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
  "strTags": "Meat,Pie",
  "strYoutube": "https://www.youtube.com/watch?v=nMyBC9staMU",
  "strIngredient1": "Beef",
  "strIngredient2": "Plain Flour",
  "strIngredient3": "Rapeseed Oil",
  "strIngredient4": "Red Wine",
  "strIngredient5": "Beef Stock",
  "strIngredient6": "Onion",
  "strIngredient7": "Carrots",
  "strIngredient8": "Thyme",
  "strIngredient9": "Mustard",
  "strIngredient10": "Egg Yolks",
  "strIngredient11": "Puff Pastry",
  "strIngredient12": "Green Beans",
  "strIngredient13": "Butter",
  "strIngredient14": "Salt",
  "strIngredient15": "Pepper",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "1kg",
  "strMeasure2": "2 tbs",
  "strMeasure3": "2 tbs",
  "strMeasure4": "200ml",
  "strMeasure5": "400ml",
  "strMeasure6": "1 finely sliced",
  "strMeasure7": "2 chopped",
  "strMeasure8": "3 sprigs",
  "strMeasure9": "2 tbs",
  "strMeasure10": "2 free-range",
  "strMeasure11": "400g",
  "strMeasure12": "300g",
  "strMeasure13": "25g",
  "strMeasure14": "pinch",
  "strMeasure15": "pinch",
  "strMeasure16": "",
  "strMeasure17": "",
  "strMeasure18": "",
  "strMeasure19": "",
  "strMeasure20": "",
  "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_mustard_pie_58002",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
},{
  "idMeal": "52878",
  "strMeal": "Beef and Oyster pie",
  "strDrinkAlternate": null,
  "strCategory": "Beef",
  "strArea": "British",
  "strInstructions": "Season the beef cubes with salt and black pepper. Heat a tablespoon of oil in the frying pan and fry the meat over a high heat. Do this in three batches so that you don’t overcrowd the pan, transferring the meat to a large flameproof casserole dish once it is browned all over. Add extra oil if the pan seems dry.\r\nIn the same pan, add another tablespoon of oil and cook the shallots for 4-5 minutes, then add the garlic and fry for 30 seconds. Add the bacon and fry until slightly browned. Transfer the onion and bacon mixture to the casserole dish and add the herbs.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nPour the stout into the frying pan and bring to the boil, stirring to lift any stuck-on browned bits from the bottom of the pan. Pour the stout over the beef in the casserole dish and add the stock. Cover the casserole and place it in the oven for 1½-2 hours, or until the beef is tender and the sauce is reduced.\r\nSkim off any surface fat, taste and add salt and pepper if necessary, then stir in the cornflour paste. Put the casserole dish on the hob – don’t forget that it will be hot – and simmer for 1-2 minutes, stirring, until thickened. Leave to cool.\r\nIncrease the oven to 200C/400F/Gas 6. To make the pastry, put the flour and salt in a very large bowl. Grate the butter and stir it into the flour in three batches. Gradually add 325ml/11fl oz cold water – you may not need it all – and stir with a round-bladed knife until the mixture just comes together. Knead the pastry lightly into a ball on a lightly floured surface and set aside 250g/9oz for the pie lid.\r\nRoll the rest of the pastry out until about 2cm/¾in larger than the dish you’re using. Line the dish with the pastry then pile in the filling, tucking the oysters in as well. Brush the edge of the pastry with beaten egg.\r\nRoll the remaining pastry until slightly larger than your dish and gently lift over the filling, pressing the edges firmly to seal, then trim with a sharp knife. Brush with beaten egg to glaze. Put the dish on a baking tray and bake for 25-30 minutes, or until the pastry is golden-brown and the filling is bubbling.",
  "strMealThumb": "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
  "strTags": "Pie",
  "strYoutube": "https://www.youtube.com/watch?v=ONX74yP6JnI",
  "strIngredient1": "Beef",
  "strIngredient2": "Olive Oil",
  "strIngredient3": "Shallots",
  "strIngredient4": "Garlic",
  "strIngredient5": "Bacon",
  "strIngredient6": "Thyme",
  "strIngredient7": "Bay Leaf",
  "strIngredient8": "Stout",
  "strIngredient9": "Beef Stock",
  "strIngredient10": "Corn Flour",
  "strIngredient11": "Oysters",
  "strIngredient12": "Plain Flour",
  "strIngredient13": "Salt",
  "strIngredient14": "Butter",
  "strIngredient15": "Eggs",
  "strIngredient16": "",
  "strIngredient17": "",
  "strIngredient18": "",
  "strIngredient19": "",
  "strIngredient20": "",
  "strMeasure1": "900g",
  "strMeasure2": "3 tbs",
  "strMeasure3": "3",
  "strMeasure4": "2 cloves minced",
  "strMeasure5": "125g",
  "strMeasure6": "1 tbs chopped",
  "strMeasure7": "2",
  "strMeasure8": "330ml",
  "strMeasure9": "400ml",
  "strMeasure10": "2 tbs",
  "strMeasure11": "8",
  "strMeasure12": "400g",
  "strMeasure13": "pinch",
  "strMeasure14": "250g",
  "strMeasure15": "To Glaze",
  "strMeasure16": "",
  "strMeasure17": "",
  "strMeasure18": "",
  "strMeasure19": "",
  "strMeasure20": "",
  "strSource": "https://www.bbc.co.uk/food/recipes/beef_and_oyster_pie_65230",
  "strImageSource": null,
  "strCreativeCommonsConfirmed": null,
  "dateModified": null
}];